# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# connection string for PostgreSQL on Render (External URL for local use)
sqlalchemy.url = postgresql://spms_user:iOodN3nJDpbzkYulYWHXxvBmpdKMYN2v@dpg-d5f9coi4d50c73cke4l0-a.frankfurt-postgres.render.com:5432/spms_db_6fqn

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# version path separator
version_path_separator = os

# output encoding used when revision files are written
output_encoding = utf-8


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
