# backend/utils/pdf_generator.py
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from pathlib import Path

def add_logo_to_pdf(c, logo_path: str = None):
    """Add SPMS logo to PDF"""
    if not logo_path:
        logo_path = Path(__file__).parent.parent.parent / "frontend" / "src" / "images" / "logo.png"
    
    width, height = letter
    
    try:
        c.drawImage(str(logo_path), 
                   x=50, 
                   y=height - 100, 
                   width=150, 
                   height=60,
                   preserveAspectRatio=True)
    except Exception as e:
        # If logo not found, just add text
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 70, "SPMS")
    
    # Add title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(220, height - 70, "Smart Participants Management System")
    c.line(50, height - 110, width - 50, height - 110)

def create_sample_report(filename: str = "sample_report.pdf"):
    """Create a sample PDF report with logo"""
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    
    # Add logo and header
    add_logo_to_pdf(c)
    
    # Add content
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 150, "Monthly Activity Report")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 180, "Date: December 2024")
    c.drawString(50, height - 200, "Generated by: SPMS System")
    
    # Add more content here...
    
    c.save()
    return filename