"""Initial migration

Revision ID: f849e0cb7d1f
Revises: 
Create Date: 2025-12-25 07:08:02.410636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f849e0cb7d1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(length=200), nullable=False),
    sa.Column('community', sa.String(length=200), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=200), nullable=False),
    sa.Column('gps_lat', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('gps_lon', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('origin_address', sa.Text(), nullable=True),
    sa.Column('special_judicial_needs', sa.Boolean(), nullable=True),
    sa.Column('economically_depressed', sa.Boolean(), nullable=True),
    sa.Column('food_insecure', sa.Boolean(), nullable=True),
    sa.Column('shelter_insecure', sa.Boolean(), nullable=True),
    sa.Column('war_persecution_affected', sa.Boolean(), nullable=True),
    sa.Column('disaster_affected', sa.Boolean(), nullable=True),
    sa.Column('highly_vulnerable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_programmes_id'), 'programmes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('admin', 'staff', 'participant'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('household_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('M', 'F'), nullable=False),
    sa.Column('relationship', sa.Enum('Head', 'Aunt', 'Child', 'Common-law partner', 'Cousin', 'Grandchild', 'Grandparent', 'Nephew', 'Niece', 'Other', 'Parent', 'Sibling', 'Spouse', 'Uncle'), nullable=False),
    sa.Column('marital_status', sa.Enum('Divorced', 'Living common-law', 'Married', 'Separated', 'Single', 'Widowed'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=False),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_id', sa.String(length=18), nullable=True),
    sa.Column('gov_id_type', sa.Enum('National ID', 'Driving License', 'ID Card', 'NIF', 'NRC', 'Passport'), nullable=True),
    sa.Column('gov_id_number', sa.String(length=32), nullable=True),
    sa.Column('phone_carrier', sa.Enum('Airtel', 'MTN', 'Other'), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('payment_agency', sa.Enum('Airtel Money', 'MTN Mobile Money', 'Bank', 'None'), nullable=True),
    sa.Column('payment_agency_type', sa.Enum('Mobile Money', 'Bank', 'None'), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('client_number', sa.String(length=50), nullable=True),
    sa.Column('is_idp', sa.Boolean(), nullable=True),
    sa.Column('is_migrant', sa.Boolean(), nullable=True),
    sa.Column('is_refugee', sa.Boolean(), nullable=True),
    sa.Column('is_refugee_claimant', sa.Boolean(), nullable=True),
    sa.Column('is_returnee', sa.Boolean(), nullable=True),
    sa.Column('malnourished', sa.Boolean(), nullable=True),
    sa.Column('pregnant', sa.Boolean(), nullable=True),
    sa.Column('lactating', sa.Boolean(), nullable=True),
    sa.Column('hiv_aids', sa.Boolean(), nullable=True),
    sa.Column('tb', sa.Boolean(), nullable=True),
    sa.Column('other_chronic_illness', sa.Boolean(), nullable=True),
    sa.Column('needs_medical_attention', sa.Boolean(), nullable=True),
    sa.Column('needs_psychological_counselling', sa.Boolean(), nullable=True),
    sa.Column('permanent_physical_disability', sa.Boolean(), nullable=True),
    sa.Column('mental_disability', sa.Boolean(), nullable=True),
    sa.Column('temporarily_incapacitated', sa.Boolean(), nullable=True),
    sa.Column('limited_strength_mobility', sa.Boolean(), nullable=True),
    sa.Column('orphan', sa.Boolean(), nullable=True),
    sa.Column('minor_worst_forms_child_labour', sa.Boolean(), nullable=True),
    sa.Column('minor_not_attending_school', sa.Boolean(), nullable=True),
    sa.Column('unaccompanied_by_adult', sa.Boolean(), nullable=True),
    sa.Column('needs_protection', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_members_assigned_id'), 'household_members', ['assigned_id'], unique=True)
    op.create_index(op.f('ix_household_members_id'), 'household_members', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('related_module', sa.Enum('attendance', 'survey', 'me', 'casemanagement', 'project', 'programme', 'activity', 'registration'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('me_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('current_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_me_indicators_id'), 'me_indicators', ['id'], unique=False)
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN', 'OUT'), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_id'), 'case_notes', ['id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_case_notes_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_surveys_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_me_indicators_id'), table_name='me_indicators')
    op.drop_table('me_indicators')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_household_members_id'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_assigned_id'), table_name='household_members')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_programmes_id'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.drop_table('households')
    # ### end Alembic commands ###
